# Site settings
title: Art by Paige
description: demo site with art by my 2-year-old.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site
author: J.Lam

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/paigebydj/
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Plugins
# https://github.com/brockfanning/jekyll-get-json
plugins:
  - jekyll-get-json

# Get JSON data
# Replace PPI json url with the one with your username
jekyll_get_json:
  - data: images
    json: https://profilepageimages.usecue.com/images/paigebydj/images.json

# Build settings
markdown: kramdown
