# Site settings
<<<<<<< HEAD
title: Art by Paige
description: 2 Year Old School Art
baseurl: '' # the subpath of your site, e.g. /blog
=======
title: Lens
description: Just another fine responsive site template by <a href="http://html5up.net">HTML5 UP</a> with Instagram images loaded using <a href="https://profilepageimages.usecue.com">PPI</a>.
baseurl: '/lens-jekyll-theme' # the subpath of your site, e.g. /blog
>>>>>>> master
url: '' # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

# Plugins
# https://github.com/brockfanning/jekyll-get-json
plugins:
  - jekyll-get-json

# Get JSON data
# Replace PPI json url with the one with your username
jekyll_get_json:
  - data: images
    json: 'https://profilepageimages.usecue.com/images/paigebydj/images.json'
